version: '3.6'
services:
  mongodb:
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - /tmp/pippo/:/data/db/
    image: mongo:4.2.14
    container_name: mongodb-server
    hostname: mongodb
    networks:          
    - mailqueue-go-net
  mailqueue-go-poll:
    build:
      context: ./
      dockerfile: poll.Dockerfile
      target: prod
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    image: mailqueue-go-poll
    container_name: mailqueue-go-poll
    hostname: mailqueue-go-poll          
    networks:          
      - mailqueue-go-net
    env_file:
      - .env     
  mailqueue-go-api:
    build:
      context: ./
      dockerfile: api.Dockerfile
      target: prod
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    image: mailqueue-go-api
    container_name: mailqueue-go-api
    hostname: mailqueue-go-api
    ports:
      - 8080:8080
    networks:          
      - mailqueue-go-net
    env_file:
      - .env     

networks:
  mailqueue-go-net:
    external: false  

