version: '3.6'
services:
  mongodb:
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - /tmp/pippo/:/data/db/
    image: mongo:4.2.14
    container_name: mongodb
    hostname: mongodb
    networks:          
    - mailqueue-go-net
  mailqueue-go-poll:
    build:
      context: ./
      target: prod
      args:
        - TYPE=poll
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    image: mailqueue-go-poll
    container_name: mailqueue-go-poll
    hostname: mailqueue-go-poll          
    environment:
      - MONGO_ENDPOINT=mongodb://admin:pass@mongodb:27017/admin?authSource=admin
      - MONGO_DB=test
      - MONGO_DB_SIZE=1000000
      - MONGO_TIMEOUT=10
      - SMTP_ALLOW=10
      - SMTP_INTERVAL_MINUTE=1      
      - SMTP_SERVER=localhost
      - SMTP_USERNAME=username@localhost
      - SMTP_PASSWORD=password
      - SMTP_FROM=username@localhost
      - SMTP_FROMNAME=fromname
      - SMTP_REPLYTO=noreply@localhost
      - SMTP_ATTEMPTS=3
      - LOG_OUTPUT=stdout
    networks:          
      - mailqueue-go-net         
  mailqueue-go-api:
    build:
      context: ./
      target: prod
      args:
        - TYPE=api
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    image: mailqueue-go-api
    container_name: mailqueue-go-api
    hostname: mailqueue-go-api
    ports:
      - 8080:8080
    environment:
      - MONGO_ENDPOINT=mongodb://admin:pass@mongodb:27017/admin?authSource=admin
      - MONGO_DB=test
      - MONGO_DB_SIZE=1000000
      - MONGO_TIMEOUT=10
      - BIND_ADDRESS=:8080
      - LOG_OUTPUT=stdout
    networks:          
      - mailqueue-go-net

networks:
  mailqueue-go-net:
    external: true  

